import { Download, ExternalLink, MoreHorizontal } from "lucide-react";

import { Panel, TinyTag } from "@/components/report-builder/ReportBuilderPrimitives";
import type { ExportHistoryItem } from "@/types/report-builder";

type ExportHistoryTableProps = {
  exports: ExportHistoryItem[];
};

export function ExportHistoryTable({ exports }: ExportHistoryTableProps) {
  return (
    <Panel title="Export History">
      <div className="overflow-hidden">
        <table className="w-full table-fixed text-left text-sm">
          <thead className="bg-slate-50 text-xs font-semibold text-slate-600">
            <tr>
              <th className="w-[180px] px-4 py-3">Format</th>
              <th className="w-[140px] px-4 py-3">Status</th>
              <th className="px-4 py-3">File Asset</th>
              <th className="w-[110px] px-4 py-3">Size</th>
              <th className="w-[160px] px-4 py-3">Generated By</th>
              <th className="w-[200px] px-4 py-3">Deterministic Renderer</th>
              <th className="w-[210px] px-4 py-3">Generated At</th>
              <th className="w-[78px] px-4 py-3" />
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100">
            {exports.map((item) => (
              <tr key={item.id} className="hover:bg-slate-50/80">
                <td className="px-4 py-3">
                  <span className="mr-2 text-slate-700">{item.format}</span>
                  <TinyTag>{item.kind}</TinyTag>
                </td>
                <td className="px-4 py-3">
                  <span className="rounded-md border border-emerald-200 bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-700">
                    {item.status}
                  </span>
                </td>
                <td className="px-4 py-3">
                  <a href="#asset" className="inline-flex min-w-0 items-center gap-1 font-semibold text-blue-600 hover:text-blue-700">
                    <span className="truncate">{item.fileName}</span>
                    <ExternalLink className="h-3.5 w-3.5 shrink-0" />
                  </a>
                </td>
                <td className="px-4 py-3 text-slate-700">{item.size}</td>
                <td className="px-4 py-3 text-slate-700">{item.generatedBy}</td>
                <td className="px-4 py-3 text-slate-700">{item.renderer}</td>
                <td className="px-4 py-3 text-slate-600">{item.generatedAt}</td>
                <td className="px-4 py-3">
                  <span className="flex items-center justify-end gap-3 text-slate-500">
                    <Download className="h-4 w-4" />
                    <MoreHorizontal className="h-4 w-4" />
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>
        <div className="flex h-10 items-center justify-between border-t border-slate-100 px-4 text-xs text-slate-500">
          <span>{exports.length} exports</span>
          <span>
            Exports are stored as file assets and immutable.
            <button type="button" className="ml-4 font-semibold text-blue-600 hover:text-blue-700">
              View in File Assets
            </button>
          </span>
        </div>
      </div>
    </Panel>
  );
}
